### ISSUE TITLE
4:3 aspect ratio ScreenGameplay cleanup?

### ISSUE THREAD

**Issue by Horsey-** [Horsey-/Simply-Love-SM5-1#1]
@dguzek

![2019-09-22 14_24_14-Window](https://user-images.githubusercontent.com/5679966/65394695-f1c1c280-dd45-11e9-8f77-121f92ae856b.png)

**Issue 1**

Arrows draw above all elements: I thought I read somewhere that this was done to preserve the ability for FGchanges to work properly. Is it possible though to preserve this functionality by using draworder to put arrows below the top elements of the screen [lifebar, score, NPS graph, difficulty number]?

**Solutions**
1. Use draworder to layer the steps below the other elements.

2. This behaviour should be changed in the stepmania engine so that the arrows follow the 3.95 behaviour of fading out rapidly once they pass over the arrow receptor.

3. The theme manipulates the steps and receptors such that we achieve this hiding behaviour theme-side.

**Issue 2**
In 4:3 aspect ratio, there is no room to display the pacemaker numbers, instead they just overflow on top of the BPM

**Solutions**

1. In 4:3 aspect ratio, wouldn't it be prudent to push down the EVENT text further to the bottom and shrink the pacemaker text? Would it be better to shrink down this text and make it fit both texts on the same line? (like the rough sketch below)
![move1](https://user-images.githubusercontent.com/5679966/65394911-32bad680-dd48-11e9-9521-fdef0316716d.png)

2. Pacemaker text should not be able to be enabled with the NPS graph on top in 4:3, with no NPS graph there is more than enough space for the pacemaker text.
![image](https://user-images.githubusercontent.com/5679966/65394976-47e43500-dd49-11e9-883f-0d4d675468eb.png)

3. This theme does not officially support 4:3 aspect ratio any longer.

**Comment by quietly-turning** [comment]
I am not interested in working on this right now.

**Comment by quietly-turning** [comment]
To clarify in a more honest way: 
I do not have the emotional wherewithal to work with you on Simply Love right now.  I'm sorry.
Please accept this.

**Comment by Horsey-** [comment]
If I find the time I'll just submit a pull request; I don't use 4:3 but wanted to point out the issue in case someone ever wants to install this theme on a 4:3 machine.

**Comment by Horsey-** [comment]
I don't really want to spend time on 4:3 aspect ratio since it's a legacy option anyway. As far as I know, there are no new 4:3 monitors being released with higher resolutions than 1080p equivalent. Unless there is a future usecase that makes sense, I'm going to just leave 4:3 as-is.
